import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import styles from '/styles/Layout.module.css'

export default function Layout({ children, title }) {
  const { asPath } = useRouter()
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.layout_main}>
        <nav className={styles.layout_nav}>
          <div className={styles.layout_btn_group}>
            <Link className={`${styles.link} ${asPath == '/' ? styles.selected : ''}`} href='/'>Home</Link>
            <Link className={`${styles.link} ${asPath == '/favorites' ? styles.selected : ''}`} href='/favorites'>Favs</Link>
          </div>
          <h1 className={styles.title}>CryptoTracker</h1>
          <div className={styles.layout_btn_group}>
            <Link className={`${styles.link} ${asPath == '/about' ? styles.selected : ''}`} href='/about'>About</Link>
          </div>
        </nav>
        {
          children
        }
      </main>
    </>
  )
}